// d1-todos/apps/qwik-city/src/routes/index.tsx
import {
  component$,
  Resource,
  useClientEffect$,
  useSignal,
  useStore,
} from "@builder.io/qwik";
import { RequestHandler, useEndpoint } from "@builder.io/qwik-city";
import {
  type Todo,
  getTodos,
  addTodo,
  editTodo,
  deleteTodo,
  validateTodoText,
  getOrCreateSessionId,
  getSessionIdFromRequest,
  saveSessionIdCookie,
} from "shared";

interface Platform {
  D1_TODOS_DB: D1Database;
}

export const onGet: RequestHandler<{ todos: Todo[] }, Platform> = async ({
  request,
  platform,
}) => {
  const todosDb = getTodosDb(platform);
  const sessionId = await getOrCreateSessionId(request as Request, todosDb);
  const todos = await getTodos(todosDb, sessionId);
  return {
    sessionId,
    todos,
  };
};

export const onPost: RequestHandler<
  { todos: Todo[]; error?: string },
  Platform
> = async ({ request, platform }) => {
  const sessionId = getSessionIdFromRequest(request as Request);

  const formData = await request.formData();
  const operation = formData.get("operation") as "add" | "edit" | "delete";
  let error: string | null = null;

  let todos: Todo[] = [];
  const db = getTodosDb(platform);

  if (!sessionId) {
    error = "Session id not provided";
  } else {
    try {
      const operationFn = operationFnsMap[operation];
      await operationFn(formData, db, sessionId);
      todos = await getTodos(db, sessionId);
    } catch (e: any) {
      error = e.message;
    }
  }

  return {
    todos,
    ...(error ? { error } : {}),
  };
};

const operationFnsMap = {
  add: handleTodoAdd,
  edit: handleTodoEdit,
  delete: handleTodoDelete,
} as const;

async function handleTodoAdd(
  formData: FormData,
  db: D1Database,
  sessionId: string
): Promise<void> {
  const text = formData.get("text") as string;
  const checkResult = validateTodoText(text);
  if (checkResult.valid) {
    try {
      await addTodo(db, sessionId, text);
    } catch {
      throw new Error("DataBase Internal Error");
    }
  } else {
    throw new Error(checkResult.reason!);
  }
}

async function handleTodoEdit(
  formData: FormData,
  db: D1Database,
  sessionId: string
): Promise<void> {
  const id = formData.get("todo-id") as string;
  const completed = (formData.get("completed") as string) === "true";
  try {
    await editTodo(db, sessionId, id, completed);
  } catch {
    throw new Error("DataBase Internal Error");
  }
}

async function handleTodoDelete(
  formData: FormData,
  db: D1Database,
  sessionId: string
): Promise<void> {
  const id = formData.get("todo-id") as string;
  try {
    await deleteTodo(db, sessionId, id);
  } catch {
    throw new Error("DataBase Internal Error");
  }
}

export default component$(() => {
  const data = useEndpoint<{
    sessionId: string;
    todos: Todo[];
    error?: string;
  }>();

  const newTodo = useSignal<string>("");
  const sessionState = useStore({ sessionId: "" });

  useClientEffect$(({ track }) => {
    track(sessionState);

    if (sessionState.sessionId) {
      saveSessionIdCookie(sessionState.sessionId);
    }
  });

  return (
    <Resource
      value={data}
      onPending={() => <div></div>}
      onRejected={() => <div></div>}
      onResolved={({ sessionId, todos, error }) => {
        if (sessionId) {
          sessionState.sessionId = sessionId;
        }

        return (
          <div class="todos-app">
            <h1>Todos</h1>
            <form method="post" class="add-todo-wrapper">
              <div class="new-todo-input-form-control">
                <input hidden name="operation" readOnly value="add" />
                <input
                  class={
                    !newTodo.value || validateTodoText(newTodo.value).valid
                      ? ""
                      : "invalid"
                  }
                  type="text"
                  name="text"
                  value={newTodo.value}
                  onInput$={(event) => {
                    newTodo.value = (
                      event.target as unknown as { value: string }
                    ).value;
                  }}
                />
                <button disabled={!newTodo.value}>add todo</button>
              </div>
            </form>
            {error && <p class="backend-error">{error}</p>}
            <ul>
              {todos.map(({ id, text, completed }) => (
                <li key={id}>
                  <form method="post">
                    <input hidden name="operation" readOnly value="edit" />
                    <input hidden name="todo-id" readOnly value={id} />
                    <input
                      hidden
                      name="completed"
                      readOnly
                      value={`${!completed}`}
                    />
                    <button
                      role="checkbox"
                      aria-checked={completed}
                      aria-label={text}
                      class={`custom-checkbox ${completed ? "checked" : ""}`}
                    ></button>
                  </form>
                  <span class={completed ? "line-through" : ""}>{text}</span>
                  <form method="post">
                    <input hidden name="operation" readOnly value="delete" />
                    <input hidden name="todo-id" readOnly value={id} />
                    <button class="delete-btn" aria-label="delete"></button>
                  </form>
                </li>
              ))}
            </ul>
          </div>
        );
      }}
    />
  );
});

function getTodosDb(platform: Platform): D1Database {
  return platform["D1_TODOS_DB"] as D1Database;
}

// d1-todos/apps/remix/app/routes/index.tsx
import { type AppLoadContext } from "@remix-run/cloudflare";
import { type DataFunctionArgs } from "@remix-run/cloudflare";
import {
  Form,
  useActionData,
  useLoaderData,
  useTransition,
} from "@remix-run/react";
import { type ChangeEvent, useEffect, useState } from "react";
import {
  type Todo,
  getTodos,
  addTodo,
  editTodo,
  deleteTodo,
  validateTodoText,
  getOrCreateSessionId,
  getSessionIdFromRequest,
  saveSessionIdCookie,
} from "shared";
import styles from "shared/src/styles.css";

export function links() {
  return [{ rel: "stylesheet", href: styles }];
}

// Note: for the loader and action we are not suing the LoaderFunction and ActionFunction
//       types but just DataFunctionArgs so that we can infer the return type and have good type safety
//       (see: https://jfranciscosousa.com/blog/typing-remix-loaders-with-confidence)

export async function loader({ request, context }: DataFunctionArgs) {
  const todosDb = getTodosDb(context);
  const sessionId = await getOrCreateSessionId(request, todosDb);
  const todos = await getTodos(todosDb, sessionId);
  return {
    sessionId,
    todos,
  };
}

type ActionResult = { success: boolean; errorMessage?: string };

export async function action({
  context,
  request,
}: DataFunctionArgs): Promise<ActionResult> {
  const sessionId = getSessionIdFromRequest(request);

  if (!sessionId) {
    return {
      success: false,
      errorMessage: "Session id not provided",
    };
  }

  // Note: we are using the method here since Remix provides it and the verbs here match
  //       nicely the various operations, we could have also used actions or hidden fields
  //       to distinguish the various operations
  if (request.method === "POST") {
    return handlePostAction(request, sessionId, context);
  }
  if (request.method === "PATCH") {
    return handlePutAction(request, sessionId, context);
  }
  if (request.method === "DELETE") {
    return handleDeleteAction(request, sessionId, context);
  }

  throw new Error("Method not supported");
}

async function handlePostAction(
  request: Request,
  sessionId: string,
  context: AppLoadContext
): Promise<ActionResult> {
  const formData = await request.formData();
  const text = formData.get("text") as string;

  if (!text) {
    return {
      success: false,
      errorMessage: "Todos can't be empty",
    };
  }

  const textValidation = validateTodoText(text);
  if (!textValidation.valid) {
    return {
      success: false,
      errorMessage: textValidation.reason,
    };
  }

  try {
    await addTodo(getTodosDb(context), sessionId, text as string);
  } catch {
    return {
      success: false,
      errorMessage: "DataBase Internal Error",
    };
  }

  return { success: true };
}

async function handlePutAction(
  request: Request,
  sessionId: string,
  context: AppLoadContext
): Promise<ActionResult> {
  const formData = await request.formData();
  const todoId = formData.get("todo-id");
  const completed = formData.get("completed");

  if (!todoId) {
    return {
      success: false,
      errorMessage: "the id of the todo must be provided",
    };
  }

  if (!completed) {
    return {
      success: false,
      errorMessage: "the completed status for the todo must be provided",
    };
  }

  try {
    await editTodo(
      getTodosDb(context),
      sessionId,
      todoId as string,
      completed === "true"
    );
  } catch {
    return {
      success: false,
      errorMessage: "DataBase Internal Error",
    };
  }

  return { success: true };
}

async function handleDeleteAction(
  request: Request,
  sessionId: string,
  context: AppLoadContext
): Promise<ActionResult> {
  const formData = await request.formData();
  const todoId = formData.get("todo-id");

  if (!todoId) {
    return {
      success: false,
      errorMessage: "the id of the todo must be provided",
    };
  }

  try {
    await deleteTodo(getTodosDb(context), sessionId, todoId as string);
  } catch {
    return {
      success: false,
      errorMessage: "DataBase Internal Error",
    };
  }

  return { success: true };
}

type LoaderType = Awaited<ReturnType<typeof loader>>;
type ActionType = Awaited<ReturnType<typeof action>>;

export default function Index() {
  const { sessionId, todos }: { sessionId: string; todos: Todo[] } =
    useLoaderData<LoaderType>();

  useEffect(() => saveSessionIdCookie(sessionId), [sessionId]);

  const transition = useTransition();

  const actionData = useActionData<ActionType>();
  let error = actionData?.errorMessage ?? null;

  const [newTodo, setNewTodo] = useState("");

  useEffect(() => {
    if (
      transition.state === "loading" &&
      transition.submission?.method === "POST" &&
      !error
    ) {
      setNewTodo("");
    }
  }, [transition.state, transition.submission, error]);

  return (
    <div className="todos-app">
      <h1>Todos</h1>
      <div>
        <Form method="post">
          <div className="new-todo-input-form-control">
            <input
              className={
                !newTodo || validateTodoText(newTodo).valid ? "" : "invalid"
              }
              type="text"
              name="text"
              value={newTodo}
              onInput={(event: ChangeEvent<HTMLInputElement>) =>
                setNewTodo(event.target.value)
              }
            />
            <button disabled={!newTodo}>add todo</button>
          </div>
        </Form>
        {error && <p className="backend-error">{error}</p>}
      </div>
      <ul>
        {todos.map(({ id, text, completed }) => (
          <li key={id}>
            <Form method="patch">
              <input hidden name="todo-id" readOnly value={id} />
              <input hidden name="completed" readOnly value={`${!completed}`} />
              <button
                role="checkbox"
                aria-checked={completed}
                aria-label={text}
                className={`custom-checkbox ${completed ? "checked" : ""}`}
              ></button>
            </Form>
            <span className={completed ? "line-through" : ""}>{text}</span>
            <Form method="delete">
              <input hidden name="todo-id" readOnly value={id} />
              <button className="delete-btn" aria-label="delete"></button>
            </Form>
          </li>
        ))}
      </ul>
    </div>
  );
}

function getTodosDb(context: AppLoadContext): D1Database {
  return context["D1_TODOS_DB"] as D1Database;
}
